// ─────────────────────────────────────────────────────────────────────────────
// Investor data source (frontend seam)
//
// This is the SINGLE place the UI gets investor data from. Today it returns the
// mock data in ./mockData. When the backend is live, swap the body of
// getInvestors() to fetch the real data — nothing else in the UI changes.
//
// ─────────────────────────────────────────────────────────────────────────────
// HOLD FOR LUBA / YAASAMEEN — real-data wiring
// ─────────────────────────────────────────────────────────────────────────────
// Blocked on three things (none are frontend):
//   1. DATABASE_URL provisioned (Railway) — Kabir
//   2. seed.sql run against the DB — Luba
//   3. A GET API route the browser can call, e.g. app/api/investors/route.ts,
//      that runs lib/db.searchRelationships("") (+ scoring for suggestedAction)
//      and returns the frontend `Investor[]` shape below.
//
// Recommended: do the Relationship -> Investor mapping SERVER-SIDE inside that
// route (lib/types.ts and lib/scoring.ts are server-only). Then getInvestors()
// here becomes a thin fetch and the UI stays decoupled from the DB shape.
//
// When ready, getInvestors() becomes:
//
//   export async function getInvestors(): Promise<Investor[]> {
//     const res = await fetch("/api/investors", { cache: "no-store" });
//     if (!res.ok) throw new Error(`Failed to load investors: ${res.status}`);
//     return res.json();
//   }
//
// (Making it async will require app/page.tsx to load via useEffect with a
//  loading + error state — currently it consumes getInvestors() synchronously.)
//
// ── Backend -> frontend shape mapping (reference for the API route) ──────────
// The backend `Relationship` (lib/types.ts) differs from the frontend `Investor`:
//   - One Relationship = one (fund x portfolio_company) pair. The investor list
//     groups multiple relationships by fund into a single Investor card.
//   - Signal.type is snake_case ("co_investment"); weight is lowercase ("high").
//   - Relationship has no `suggestedAction` — it is generated by the scoring /
//     MCP layer and must be supplied alongside the relationship.
//   - Relationship.lastSignalDate maps directly to Investor.lastSignalDate.
//
// Sketch (implement server-side, grouping Relationship[] by fund):
//
//   function relationshipToInvestor(r: Relationship, suggestedAction: string): Investor {
//     return {
//       id: r.id,
//       name: r.fund?.name ?? "",
//       fund: { id: r.fundId, name: r.fund?.name ?? "" },
//       warmthTier: r.warmthTier,
//       lastSignalDate: r.lastSignalDate,            // already the authoritative value
//       suggestedAction,                              // from scoring/MCP layer
//       signals: (r.signals ?? []).map(mapSignal),    // map snake_case -> UI types
//       coInvestments: deriveCoInvestments(r),        // from co_investment signals + pc
//     };
//   }
// ─────────────────────────────────────────────────────────────────────────────

import { mockInvestors, type Investor } from "./mockData";

/**
 * Returns all investors for the list view.
 *
 * Currently returns mock data (see mockData.ts, aligned to seed.sql).
 * Swap the body to fetch /api/investors when the backend is live — see the
 * HOLD FOR LUBA / YAASAMEEN block above.
 */
export function getInvestors(): Investor[] {
  return mockInvestors;
}
